version: '3.8'
services:
  currency-converter:
    container_name: currency-converter
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/data/data.db
      - EXCHANGE_RATE_BASE_URL=https://open.er-api.com/v6/latest
    volumes:
      - db-data:/data
volumes:
  db-data:
